name = "wenti-namecard-agent"
main = "index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[observability.logs]
enabled = true

# Configuration for different environments
[env.production]
name = "wenti-namecard-agent-prod"
# Production-specific settings can go here

[env.development]
name = "wenti-namecard-agent-dev"
# Development-specific settings can go here

# Define environment variables (non-sensitive)
[env.production.vars]
NODE_ENV = "production"
WEBHOOKPATH = "/telegram-webhook"
# WEBHOOKURL is dynamically set from the request URL in index.js (no need to hardcode)

[env.development.vars]
NODE_ENV = "development"
WEBHOOKPATH = "/telegram-webhook"
# For development, we'll use a local URL that can be overridden with --var
WEBHOOKURL = "http://localhost:8787"

# Important: Create your own KV namespace in Cloudflare dashboard and replace this ID
# Run: wrangler kv:namespace create WENTI_SECRET_STORE
[[kv_namespaces]]
binding = "WENTI_SECRET_STORE" 
# Replace with your own KV namespace ID
id = "YOUR_KV_NAMESPACE_ID"



# For sensitive variables, use Cloudflare Dashboard or wrangler secret command:
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put OPENAI_API_KEY
# wrangler secret put GOOGLE_SHEETS_ID
# wrangler secret put GOOGLE_SERVICE_ACCOUNT_EMAIL
# wrangler secret put GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY

# Optional: Add KV namespace for data storage
# Replace YOUR_KV_NAMESPACE_ID with the actual ID from Cloudflare Dashboard
# [[kv_namespaces]]
# binding = "BUSINESS_CARDS"
# id = "YOUR_KV_NAMESPACE_ID"
# preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"  # For development environment

# Customize the build if needed
[build]
command = "npm install"