name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci || npm install
      
      - name: Create deployment package
        run: |
          mkdir -p dist
          cp -r usecases handlers utils index.js package.json dist/
          cd dist && npm ci --omit=dev || npm install --omit=dev
          zip -r ../function.zip .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Deploy to Lambda
        run: |
          # Determine environment from branch
          FUNCTION_NAME=${{ vars.FUNCTION_NAME }}
          
          # Update Lambda function code
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://function.zip